apiato/core

Abstracts/Requests/Request.php

Adds the logic to bypass the `hasAccess()` method for specific routes. More details here https://github.com/apiato/apiato/pull/210

add logic to bypass hasAccess if user has one of the defined roles

---

Commands/SeedDeploymentDataCommand.php

Adds a new command to easily call the DeploymentDataSeeder that generates data needed for a deployment of the application (e.g., create an admin user, create some Settings, whatever...)
Please see other PR here as well https://github.com/apiato/apiato/pull/214

add new command

---

Generator/Commands/RouteGenerator.php
Generator/Stubs/repository.stub
Generator/Stubs/route.stub

Adds a few more details to the generators.
1) the `route` generator now has an input to define which `ui` to be used (API / WEB).
2) the `route` generator now generates an `as` name for the Route. This name is as defined as follows: `UI_CONTAINER_OPERATION`. This results, for example, in: `API_User_listAllUsers`.
3) Added the `$container` property to the `Repository` stub. The value is automatically set to the `container-name`, so it does not change anything by default. However, if you have a model that has not the same name as the Container, this would create a "valid" Model / Repository / Container configuration. This specifically tackles [this issue here](https://github.com/apiato/apiato/issues/216)
Cheers!

Generators

---

Generator/Commands/ConfigurationGenerator.php
Generator/GeneratorCommand.php

This PR allows developers to load `custom stubs` for the generators instead of using the default ones.
Stubs must be placed in `/app/Ship/Generators/CustomStubs/*`
See the other PR in `apiato/apiato` as well...

[Feature] Load "Custom Stubs"

---

Generator/Commands/RouteGenerator.php
Generator/Stubs/route.stub

Hello,
When generating a route for WEB UI it always adds auth:api middleware which forces you to change it to auth:web if you are generating the route for WEB UI.

Route stub auth middleware wrong for WEB UI

---

Generator/Commands/ContainerGenerator.php
Generator/Commands/ControllerGenerator.php
Generator/Commands/RouteGenerator.php
Generator/Stubs/controllers/crud.web.stub
Generator/Stubs/routes/api.stub
Generator/Stubs/routes/generic.stub
Generator/Stubs/routes/web.id.stub

Hello,
I am using the WEB UI pretty a lot with apiato and now with the container generator it speeds up the process a lot but I see that it is not very often used and updated so I decided to help others and myself.
Changes made:
- Generate correct CRUD routes, requests and actions, phpdoc
- Allow to use `null` in stub, action, task( Ėroutes if the route does not require a new action/task (like WEB UI create/edit methods)
- Generate route based on UI: if the UI is api then generate api route with docs. If not use generic route stub
- Controller generate to pass plural model name
Known issues:
Solution: **->where('id', '[0-9]+');** at the end of the route
I have tried to make the container generator as clean as possible. I am open to suggestions how to refactor it to make it look better if …

WEB UI container generators update

---

Traits/HashIdTrait.php

This fix prevent to occur error mentioned here [Invalid argument supplied for foreach() #250](https://github.com/apiato/apiato/issues/250)
Error happens when pass single value to field marked as an array (e.g. `field.* => 1`)

Hash ID's small bug fix

---

Exceptions/Handlers/ExceptionsHandler.php

This PR fixes the `WEB UI Exception` problem.. 
Thing is, that somewhere in history this "dispatcher" to trigger specific renderer was removed..
Logic is as follows:
If the User requests `application/json` **OR** the application forces the User to use it (the config-flag `apiato.requests.force-accept-header` is set to `true`) --> use the `JSON Exception`
If this does not match, use the `WEB Exception`
Screenshot:

fix WEB UI Exceptions

---

Generator/Commands/MailGenerator.php
Generator/Stubs/mail.stub

according to apiato docs, mails should live in Mails/ folder.

fix apiato:generate:mail folder issue

---

Abstracts/Transformers/Transformer.php
Exceptions/CoreInternalErrorException.php
Exceptions/UnsupportedFractalIncludeException.php

This moves the `callINcludeMethod()` from the Ship to the Core. See the other PR in `apiato/apiato` as well ( https://github.com/apiato/apiato/pull/299 )!

move callIncludeMethod() to core

---

Abstracts/Requests/Request.php

Added a new `mapInput(array)` method for the Request.
This method, in turn, allows mapping "keys" to others. Basically, it "renames" the keys.. This also works with "nested" keys with `dot notation` (as long as they exist).
For example you can do this:
```php
$request->mapInput([
'phone.work' => 'phone1',
'phone.home' => 'phone2',
]);
``` 
This would rename the keys `phone.work` to `phone1` and `phone.home` to `phone2` respectively. 
> Heads up!
> The `mapInput()` overrides the `$request` content! Keep that in mind!
This can be combined with `sanitizeInput(['phone1', 'phone2'])` as well..

mapInput() for Requests

---

Traits/CallableTrait.php

Reverts apiato/core#43
The #43 PR is breaking style of invoking extra methods with parameters, which leads to breaking many existing applications
Discussed this with @johannesschobel and decided to revert

Revert "Fix call extra methods"

---

Abstracts/Requests/Request.php

Lets user (of Apiato) use arrays when setting up request's access property:
```php
protected $access = [
'permissions' => ['manage-users', 'create-users'],
'roles'       => ['user-manager', 'something-else'],
];
```
as well as piped string
```php
protected $access = [
'permissions' => 'manage-users|create-users',
'roles'       => 'user-manager|something-else',
];
```

Let Requests access property use arrays as well

---

Commands/FindContainerDependenciesCommand.php
Transformers/ComposerTransformer.php

Added a command to view dependencies from one container to all other `use`d or called `Apiato::call('Cont@Func',...` Container components. (see #45 for the complete description) 
This is done by loading the file and match it with a regex that finds all lines starting with `use ...` or lines that contain the apiato call but do not start with `//` or `/*`. If you can somehow optimize the regex let me know :D. (Example for the Apiato call is at: http://www.phpliveregex.com/p/m8p )
Usage: `php artisan apiato:list:dependencies app/Containers/<Name>`
Command is placed into the `Commands` dir, Transformer is placed into a new `Transformer`directory. Feel free to move those components as you wish.
Best regards,
Fabian

Find dependencies command

---

Traits/HashIdTrait.php

Fixes the `getHashedKey()` method as described in https://github.com/apiato/apiato/issues/317 .
The **new** behavior (and that should be the intended one) is as follows:
```php
$entity->getHashedKey(); // => AS BEFORE: Uses keyName (default to 'id') to calculate the hashed value!
$entity->getHashedKey(null); // => AS BEFORE: same as above
$entity->getHashedKey('id'); // uses $entity->id to calculate the hashed value
$entity->getHashedKey('customID'); // uses $entity->customID to calculate the value
$entity->getHashedKey('adfadfq'); // returns "" if the field cannot be found in this model
```
This PR should not break anything, because of the following reasons:
1) If you just used the `->getHashedKey()` method in your Transformers before, the method was called without parameter. This …

fix hashedKey()

---

Generator/Stubs/repository.stub

Since the container is automatically resolved from the class path now (one of my updates to the apiato core) there's no need to specify a container anymore in the repository class except when someone places a repository in a different container than the model but that's just bad design which we shouldn't support. So you can decide what to do with this pull request :)

update repository stub

---

Generator/Commands/ActionGenerator.php
Generator/Commands/TaskGenerator.php
Generator/GeneratorCommand.php

This PR removes the `c` and `f` option alias for `--container` and `--file`. This one is related to the issue described here https://github.com/apiato/apiato/issues/325

Remove Generator Command Alias

---

Abstracts/Requests/Request.php

This PR adds the `Request::toTransporter()` method.. This method, in turn, allows for creating a `Transporter` based on a given `Request`. Furthermore, it uses the `protected $transporter` property from `Request` in order to create the specified class..

add toTransporter method to Request

---

Generator/Commands/ConfigurationGenerator.php
Generator/Commands/ContainerApiGenerator.php
Generator/Commands/ContainerGenerator.php
Generator/Commands/ContainerWebGenerator.php
Generator/Commands/EventGenerator.php
Generator/Commands/EventHandlerGenerator.php
Generator/Commands/ExceptionGenerator.php
Generator/Commands/JobGenerator.php
Generator/Commands/MailGenerator.php
Generator/Commands/MigrationGenerator.php
Generator/Commands/ModelGenerator.php
Generator/Commands/NotificationGenerator.php
Generator/Commands/ReadmeGenerator.php
Generator/Commands/RepositoryGenerator.php
Generator/Commands/RequestGenerator.php
Generator/Commands/SeederGenerator.php
Generator/Commands/ServiceProviderGenerator.php
Generator/Commands/SubActionGenerator.php
Generator/Commands/TaskGenerator.php
Generator/Commands/TransformerGenerator.php
Generator/Commands/TransporterGenerator.php
Generator/Commands/ValueGenerator.php
Generator/GeneratorCommand.php
Generator/GeneratorsServiceProvider.php
Generator/Stubs/request.stub
Generator/Stubs/transporter.stub

This PR provides a `Generator` in order to automatically create `Transporters`..
What it does:
- It provides a Generator for the `Transporter` object
- When creating a `Request`, it asks the user if he wants to also create the corresponding `Transporter`. If he selects `yes`, he is asked for the respective classname (e.g., `UpdateUserTransporter`). This `Transporter` is then set as `protected $transporter` within the generated `Request` class! If no corresponding `Transporter` shall be created, a `// protected $transporter = DataTransporter::class;` is added in order to indicate, how this feature may be enabled! In this specific case (i.e., no `Transporter` is defined), the implementation "falls back" to the `DataTransporter` anyways.
- The `Container(API/WEB)Generators` are also adapted …

[Generator] Transporter

---

CHANGELOG.md
composer.json

Start working on a `core` that supports laravel 5.6.
Note that this PR - at first - only updates dependencies. Most of the changes may be subject to `apiato/apiato` but not to the core. However, as additional changes may be required, i will add other PRs for the core

Laravel 5.6

---

Abstracts/Actions/Action.php
Abstracts/Repositories/Repository.php
Abstracts/Tasks/Task.php
Generator/Stubs/actions/getall.stub
Generator/Stubs/tasks/create.stub
Generator/Stubs/tasks/delete.stub
Generator/Stubs/tasks/find.stub
Generator/Stubs/tasks/getall.stub
Generator/Stubs/tasks/update.stub
Traits/HasRequestCriteriaTrait.php

This PR applies changes to the `core` to fix the issue with `cascading Repositories`.
The issue here is, that the `RequestCriteria` is applied to **all** `Repositories` instead of only to one.
For example, you have a Route that does the following thing:
1) Get All Users
2) Get All Purchases for All Users
If you then call the Route like so: `GET endpoint?search=name:test` this will result in:
1) The `RequestCriteria` will be applied to the `UserRepository` **and** the `PurchaseRepository`.
2) Both repositories are filtered with `name=test`.
The result would be all users that are named `test` and only the purchases that are called `test` for them. So obvioulsy, not the thing you want..
------------
This PR does the following thing:
- It uses a configuration flag to not automatically apply …

Fix Repository

---

Generator/Stubs/job.stub

Incorrect naming on the namespace, change "Job" to "Jobs".

Fix incorrect namespace on Job stub

---

Traits/CallableTrait.php

This PR introduces a new `transactionalCall()` method with the same signature as the well-known `call()` function. However, the `transactionalCall()` wraps respective `call()` function in a `DB::transaction()` in order to keep the database in a consistent state.

transactionalCall()  method

---

Traits/CallableTrait.php

This PR introduces a new `transactionalCall()` method with the same signature as the well-known `call()` function. However, the `transactionalCall()` wraps respective `call()` function in a `DB::transaction()` in order to keep the database in a consistent state.

new TransactionalCall Method for 2.4

---

Traits/TestsTraits/PhpUnit/TestsAuthHelperTrait.php

This will allow to access `roles` and `permissions` even on test environment,
example :  `$userRolesNames = auth()->user()->getRoleNames();`
much explained with this comment
https://github.com/spatie/laravel-permission/issues/457#issuecomment-329313222
Thanks, best regards

Refresh user after assign roles/permissions on test environment

---

Loaders/SeederLoaderTrait.php

If sortSeeders return void It breaks code when there are no Seeders on the entire application since it is used in a foreach of loadSeeders method.
To reproduce the error you can delete all Apiato start seeds and run the command to seed database.
Returning a Collection fixes the problem.

Fix sortSeeders method return a Collection instead of Collection|static

---

Traits/ResponseTrait.php

This PR allow nested includes through `transform` method. 
For example: `$this->transform($users, UserTransformer::class, ['company.logo', 'company.founder.roles'])`
It will also allow front-end to pass additional includes.

Allow nested includes

---

Traits/HashIdTrait.php

Upon specific hash ids it's possible to get IDs like 4e12345 ... which is true for `is_numeric('4e12345')` and breaks the app

Remove checking for numeric hashed ids

---

Abstracts/Repositories/Repository.php

It doesn't return all entries while `$limit` is passed as `0` **(zero) integer**.
I've enabled `PAGINATION_SKIP` (true) in `ENV` file at first. Then executed the function:
`$this->repository->paginate(0);`
All I've **got the paginated list** of entries.
✔️ Adding `isset($limit)` check fixed the issue.
✔️ Tested via query params by requests and directly in Tasks.
Let me know if there's more practical way.

Fixed bug with pagination skip

---

Generator/Commands/ContainerApiGenerator.php
Generator/Commands/ContainerGenerator.php
Generator/Commands/ContainerWebGenerator.php

Fixed https://github.com/apiato/core/issues/147
I suggest this solution:
Added an optional parameter (VALUE_NONE) 'maincalled' to the commands for generating web and api containers.
This parameter will be called from the apiato:generate:container command

Fix #147 container generator

---

Traits/HashIdTrait.php

If we do have an optional parameter, thats being dehashed, if the hash is not valid, the decode would produce an empty array instead of null.
I fixed the return and also added typing for the parameter and return types. If the decoded id is bigger than `PHP_INT_MAX`, the decoder will return a string.
This might break other peoples code that expect this to return an empty array. It should not break, if its just used in bool checks, because both `null` and `[]` are falsy.

fix: return type for not decodable hashed ids

---

src/Traits/HashIdTrait.php
tests/Unit/Traits/HashIdTraitTest.php

There is an Apiato bug that prevented arrays of decoded ids to be nullable, due to the `HashIdTrait` `processField()` method working over null data. This PR fixes that.

fix: nullabe arrays of decoded ids were retrieved as [null]

---

phpunit.xml
src/Abstracts/Tests/PhpUnit/TestCase.php
src/Traits/TestTraits/PhpUnit/TestDatabaseProfilerTrait.php
tests/Unit/Abstracts/Tests/PhpUnit/TestCaseTest.php
tests/Unit/Traits/TestTraits/PhpUnit/TestDatabaseProfilerTraitTest.php

Dealing with performance and scaling issues due to poorly designed code logic can cause a lot of hard to pin problems, especially in bigger projects. This PR adds some helpers to give the tools during development and in tests to check for hidden N+1 problems.
[This PR](https://github.com/apiato/documentation/pull/106) adds the documentation for the functionality.

Adding helpers for asserting database query count

---

src/Generator/Commands/ContainerApiGenerator.php
src/Generator/Commands/ServiceProviderGenerator.php
src/Generator/Stubs/providers/main-service-provider-with-event-provider.stub
src/Generator/Stubs/providers/main-service-provider.stub

fix(generator): EventServiceProvider don't get registered correctly
