apiato/core

- Abstracts/Requests/Request.php
small fix. Threw an error if no "user" is resolved (e.g., the user is not logged in yet!)
> small fix to check, if there is a user available

- Generator/Commands/ModelGenerator.php
- Generator/Stubs/model.stub
- Traits/HasResourceKeyTrait.php
sorry, forgot another generator for the `Model`.
This PR adds the "pluralized" `resourceKey` to the model
> add pluralized resourceKey to Model Stub

- Generator/Commands/NotificationGenerator.php
- Generator/GeneratorsServiceProvider.php
- Generator/Stubs/notification.stub
A simple and A test step for making generator for Notification class.
> Generator for Notification

- Generator/Commands/JobGenerator.php
- Generator/Commands/MailGenerator.php
- Generator/GeneratorsServiceProvider.php
- Generator/Stubs/job.stub
- Generator/Stubs/mail.stub
> Job Generator

- Generator/Commands/SeederGenerator.php
- Generator/GeneratorsServiceProvider.php
- Generator/Stubs/seeder.stub
about the mail generator will fix it with the last generator
> seeder Generator

- Generator/Stubs/controllers/crud.api.stub
- Generator/Stubs/controllers/crud.web.stub
If the container name is **Address** it breaks the generations
> Fix plural naming problem in API controller generator

- Generator/GeneratorsServiceProvider.php
These changes are pointed out here https://github.com/apiato/apiato/issues/211, but the commands were not added to the proper service provider.
> Enable Event and Event Handler Generators

- Generator/Commands/ContainerApiGenerator.php
- Generator/Commands/ContainerGenerator.php
- Generator/Commands/ContainerWebGenerator.php
- Generator/Commands/MigrationGenerator.php
- Generator/Commands/ReadmeGenerator.php
- Generator/GeneratorCommand.php
- Generator/GeneratorsServiceProvider.php
- Generator/Stubs/readme.stub
> Adjustments

- Abstracts/Exceptions/Builders/BaseExceptionBuilder.php
- Abstracts/Exceptions/Formatters/BaseFormatter.php
- Exceptions/ApiatoExceptionsHandler.php
- Generator/Stubs/exception.stub
- Providers/ApiatoProvider.php
- composer.json
This is the first part of the "Better Exceptions" package..
This mainly provides the new abstract classes and requires the 3rd party package via composer... See the other PR (in apiato/apiato) for the main implementation...
Minor Changes
- added a `code` to the `exception.stub` file
> Better Exceptions

- Abstracts/Exceptions/Exception.php
- Exceptions/Formatters/ExceptionsFormatter.php
Allow devs to add `customData` to an `Exception`.
Doc will be added to the other repo soon
> allow to add customData to an Exception

- Generator/Commands/ActionGenerator.php
- Generator/Commands/TaskGenerator.php
This fixes the issue described here https://github.com/apiato/apiato/issues/280
> Fix Generator Stubs

- Generator/Commands/ValueObjectGenerator.php
- Generator/GeneratorsServiceProvider.php
- Generator/Stubs/valueobject.stub
Added a new ValueObject Generator to be called with `php artisan apiato:generate:valueobject`
> ValueObjectGenerator

- Abstracts/Exceptions/ErrorCodesTable.php
- Abstracts/Exceptions/Exception.php
This PR provides the needed adaptations to `core` in order to provide the `error codes table` feature for apiato. See the PR in `apiato/apiato` for explanation
> Error code

- Abstracts/Events/Event.php
- Abstracts/Events/Interfaces/ShouldHandle.php
- Abstracts/Events/Interfaces/ShouldHandleNow.php
- Abstracts/Events/Jobs/EventJob.php
- Abstracts/Requests/Request.php
Support for handling (including optional async handling) inside the event component.
Optional TODO's:
- add support for specifying delay & queue name
> Event Handling Support

- Traits/CallableTrait.php
This PR fixes inability to call extra methods with passing an argument as described [here](http://docs.apiato.io/miscellaneous/magical-call/)
> Fix call extra methods

- Traits/CallableTrait.php
Referencing https://github.com/apiato/core/issues/47
> Update Apiato::call log level to debug

- Traits/ResponseTrait.php
This PR should fix the `Nested Transformer Includes` bug described in https://github.com/apiato/apiato/issues/324
Can someone please revise this PR please?!
> [Fix] Nested Transformer Includes

- Generator/GeneratorCommand.php
This PR fixes https://github.com/apiato/apiato/issues/358
> GENERATOR: remove special chars from container and file name

- Generator/Commands/MigrationGenerator.php
- Generator/GeneratorCommand.php
We'll change removeSpecialChars mehtod from private to protected to allow any child classes override this method like MigrationGenerator class
> Change removeSpecialChars mehtod to protected

- Traits/HashIdTrait.php
Replaced the key return with getAttribute
Formatted to PSR2
> Moved the field check out of the config

- Loaders/RoutesLoaderTrait.php
Sort WEB route files by the name
> Maintain WEB route files name order

- Loaders/RoutesLoaderTrait.php
> merge MASTER 2.4 branch

- Generator/Stubs/migration.stub
> Drop if exists migration

- Abstracts/Events/Dispatcher/Dispatcher.php
- Abstracts/Events/Interfaces/ShouldHandleNow.php
- Abstracts/Events/Jobs/EventJob.php
Please note that i did NOT test this yet. But should work nonetheless
> fix delay & onqueue issues

- Traits/HashIdTrait.php
Added null | string type for $filed in getHashedKey()
> Added type for $field

- src/Helpers/helpers.php
- src/Traits/HashIdTrait.php
- src/Traits/TestTraits/PhpUnit/TestAssertionHelperTrait.php
> API-1053-add-new-test-assertions

- .ddev/config.yaml
Adding a ddev configuration file.
> Add ddev configuration

- src/Generator/Stubs/model.stub
This pull request removes the type declaration from the model.stub file
> Update model.stub remove type declaration

- config/apiato.php
- src/Commands/SeedDeploymentDataCommand.php
- src/Commands/SeedTestingDataCommand.php
- src/Providers/ApiatoServiceProvider.php
- src/Traits/TestTraits/PhpUnit/TestAuthHelperTrait.php
> feat(config): create publishable default configs

- src/Generator/Generator.php
- src/Generator/Traits/PrinterTrait.php
Task [API-1017](https://apiato.atlassian.net/browse/API-1017)
[API-1017]: https://apiato.atlassian.net/browse/API-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> API-1017 migrate cli to laravel prompts
